# Generated by Django 4.2.18 on 2025-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Recipe', 'verbose_name_plural': 'Recipes'},
        ),
        migrations.AlterModelOptions(
            name='steps',
            options={'verbose_name': 'Step', 'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='<django.db.models.fields.CharField>default.jpg', upload_to='Recipe/recipe_images'),
        ),
    ]
