# Generated by Django 4.2.18 on 2025-01-30 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitems',
            options={'verbose_name_plural': 'Inventory Items'},
        ),
    ]
